##
## EPITECH PROJECT, 2020
## makefile
## File description:
## make my lib
##

all:
		make -C giantman/
		make -C antman/
		make clean -C giantman/
		make clean -C antman/

clean :
		make clean -C giantman/
		make clean -C antman/

fclean :
		make fclean -C giantman/
		make fclean -C antman/

re :
		make re -C antman/
		make re -C giantman/
		make clean -C giantman/
		make clean -C antman/
